name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install Build system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses-dev cmake libffi-dev libssl-dev
          pip install --upgrade buildozer virtualenv
          pip install "cython<3.0.0"

      # Sử dụng Action được tối ưu sẵn cho Buildozer
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ToomTG-Android-App
          path: ${{ steps.buildozer.outputs.filename }}
          retention-days: 5
